// The file contents for the current environment will overwrite these during build.
// The build system defaults to the dev environment which uses `environment.ts`, but if you do
// `ng build --env=prod` then `environment.prod.ts` will be used instead.
// The list of which env maps to which file can be found in `.angular-cli.json`.

// `.env.ts` is generated by the `npm run env` command
// import env from './.env';

export const environment = {
  production: false,
  // version: env.npm_package_version + '-dev',
  version: 1.0,
  serverUrl: 'http://cicool.proappstore.com/administrator/api/',
  defaultLanguage: 'en-US',
  supportedLanguages: [
    'en-US',
    'fr-FR'
  ],
  token: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7ImlkIjoiMSJ9LCJpYXQiOjE1MzM0NzA2MzgsImV4cCI6MTUzNjA2MjYzOH0.VdzTjpcbVlHL4CmDtb16S-hxA6dbE4kXGSzmlWzdjBI',
  apiKey: 'DFSAS49D5A520F9286409DD12DB1DEB0',
  apiUrl: 'http://cicool.proappstore.com/administrator/api/'
};
