// `.env.ts` is generated by the `npm run env` command
// import env from './.env';

export const environment = {
  production: true,
  // version: env.npm_package_version,
  serverUrl: 'https://api.chucknorris.io',
  defaultLanguage: 'en-US',
  supportedLanguages: [
    'en-US',
    'fr-FR'
  ],
  token: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7ImlkIjoiMSJ9LCJpYXQiOjE1MzM0NzA2MzgsImV4cCI6MTUzNjA2MjYzOH0.VdzTjpcbVlHL4CmDtb16S-hxA6dbE4kXGSzmlWzdjBI',
  apiKey: 'DFSAS49D5A520F9286409DD12DB1DEB0',
  apiUrl: 'http://cicool.proappstore.com/administrator/api/'
};
